ispproject/ispproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('myapp.urls','myapp'),namespace='myapp')),
]

ispproject/palm/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('rpo_po',views.rpo_po)
    
    
]

ispproject/palm/models.py
from django.db import models

# Create your models here.
class Rpo_po(models.Model):
    poinvid = models.CharField(max_length=50)
    docudate = models.DateField(auto_now_add=True)
    billid = models.CharField(max_length=50)
    vendorcardid = models.CharField(max_length=50)
    typecarid = models.CharField(max_length=50)
    goodib = models.FloatField(default=0)
    goodob = models.FloatField(default=0)
    goodnet = models.FloatField(default=0)
    price1 = models.FloatField(default=0)
    amnt1 = models.FloatField(default=0)
    price2= models.FloatField(default=0)
    amnt2 = models.FloatField(default=0)
    vendorcode = models.CharField(max_length=20)
    statusbill = models.CharField(max_length=20)
    grade = models.CharField(max_length=10)
    impurity = models.CharField(max_length=5)
    scaler = models.CharField(max_length=10)
    docutype = models.CharField(max_length=50)
    
    def __str__(self):
        return self.poinvid

ispproject/palm/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Rpo_po
from django.contrib import messages
# Create your views here.
def rpo_po(request):
    return render(request,"palm/rpo_po.html")

ispproject/templates/palm/add_rpo_po.html
<!-- Add FFB  -->
<div class="modal fade"{% block modal-id %} id="add_ffb_Modal" {% endblock modal-id %} data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="add_ffb_ModalModal" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-dark">
                <h5 class="modal-title text-light font-weight-bold" id="add_ffb_ModalModal">{% block modal-title %}<i calss="fas fa-plus"></i>&nbsp;&nbsp;ข้อมูลการรับซื้อผลปาล์ม {% endblock modal-title %}</h5>
                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
            </div>
            
            <form {% block Action %} action="/add"  {% endblock Action %} method="POST"  autocomplete="off">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="row">
                        <div class="row col-md-12 mt-1">
                            <label for="level" class="form-label fw-bold">รายละเอียดบิล</label>
                            <div class="col-md-4">
                                <div class="form-group ">
                                    <input type="text" name="billid" class="form-control" placeholder="เลขที่บิล" required {% block Value-billid %} {% endblock Value-billid %}>
                                    
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group ">
                                    <input type="text" name="poinvid" class="form-control" placeholder="หมายเลข PO" required {% block Value-poinvid %} {% endblock Value-poinvid %}>
                                    
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group ">
                                    <input type="text" id="scaler" name="scaler" class="form-control" placeholder="เครื่องชั่ง"  {% block Value-scaler %} {% endblock Value-scaler %}>
                                    
                                </div>
                            </div>
                        </div>
                        <div class="row col-md-12 mt-1">
                            <label for="level" class="form-label fw-bold">ข้อมูลลูกค้า</label>
                            <div class="col-md-6">
                                <div class="form-group ">
                                    <input type="text" name="vendorcode" class="form-control" placeholder="VendorCode" required {% block Value-vendorcode %} {% endblock Value-vendorcode %}>
                                    
                                </div>
                            </div>
                         
                            <div class="col-md-6">
                                <div class="form-group ">
                                    <input type="text" name="vendorname" id="vendorname-input" class="form-control" placeholder=""  {% block Value-vendorname %} {% endblock Value-vendorname %}>
                                    
                                </div>
                            </div>
                        </div>
                        <script>
                            {% if vendorname %}
                            document.getElementById("vendorname-input").placeholder = "{{ vendorname }}";
                            {% endif %}
                        </script>
                        <div class="row col-md-12 mt-1">
                            <label for="Goodin" class="form-label fw-bold">ข้อมูลรถ</label>
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <input type="text" name="vendorcardid"  class="ml-1 form-control" autocomplete="off" required placeholder="ทะเบียนรถ" required {% block Value-vendorcardid %} {% endblock Value-vendorcardid %}>
                                        
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group ">
                                        <input type="text" name="typecarid"  class="ml-1 form-control" autocomplete="off" required placeholder="ประเภทรถ" required {% block Value-typecarid %} {% endblock Value-typecarid %}>
                                        
                                    </div>
                                </div>
                                
                                
                        </div>
                       
                            <div class="row col-md-12 mt-1">
                                <label for="Goodin" class="form-label fw-bold">ข้อมูลสินค้า</label>
                                    <div class="col-md-4">
                                        <div class="form-group ">
                                            <input type="number" id="id_goodib" name="goodib" class="form-control" placeholder="น้ำหนักเข้า" required onchange='calculateGoodNetInput()'  {% block Value-goodib %} {% endblock Value-goodib %}>
                                            
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group ">
                                            <input type="number" id="id_goodob" name="goodob" class="form-control" placeholder="น้ำหนักออก" required onchange='calculateGoodNetInput()' {% block Value-goodob %} {% endblock Value-goodob %}>
                                            
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group ">
                                            <input type="number" id="id_goodnet" name="goodnet" class="form-control" readonly  {% block Value-goodnet %}  {%endblock Value-goodnet %}>
                                            
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group ">
                                            <input type="text" id="price1" name="price1" class="form-control" placeholder="ราคา"  {% block Value-price1 %} {% endblock Value-price1 %}>
                                            
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group ">
                                            <input type="number" id="docutype" name="docutype" class="form-control" placeholder="docutype"  {% block Value-docutype %} {% endblock Value-docutype %}>
                                            
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group ">
                                            <input type="text" id="statusbill" name="statusbill" class="form-control" placeholder="statusbill"  {% block Value-statusbill %} {% endblock Value-statusbill %}>
                                            
                                        </div>
                                    </div>
                                    
                            </div>
                            <script>
                                function calculateGoodNet() {
                                    var goodib = parseFloat(document.getElementById("id_goodib").value);
                                    var goodob = parseFloat(document.getElementById("id_goodob").value);
                                    var goodnet = goodib - goodob;
                                    document.getElementById("id_goodnet").value = goodnet;
                                }
                            </script>

                            
                         
                        
                            <div class="row col-md-12 mt-1">
                                <label for="Goodin" class="form-label fw-bold">คุณภาพผลปาล์ม</label>
                                <div class="col-md-4">
                                    <div class="form-group ">
                                        <select name="grade" id="grade" class="form-select form-control"required >
                                            <option selected disabled>=== เกรด ===</option>
                                            <option value="A" {% block Value-gradea %} {% if ffb.grade == "A" %} selected {% endif %} {% endblock Value-gradea %}>A</option>
                                            <option value="B" {% block Value-gradeb %} {% if ffb.grade == "B" %} selected {% endif %} {% endblock Value-gradeb %}>B</option>
                                            <option value="C" {% block Value-gradec %} {% if ffb.grade == "C" %} selected {% endif %} {% endblock Value-gradec %}>C</option>
                                        </select>
                                        
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group ">
                                        <select name="impurity" id="impurity" class="form-select form-control" required {% block Value-impurity %} {% endblock Value-impurity %}>
                                            <option selected disabled>== สิ่งเจือปน ==</option>
                                            <option value="A" {% block Value-impuritya %} {% if ffb.impurity == "A" %} selected {% endif %} {% endblock Value-impuritya %}>A</option>
                                            <option value="B" {% block Value-impurityb %} {% if ffb.impurity == "B" %} selected {% endif %} {% endblock Value-impurityb %}>B</option>
                                            <option value="C" {% block Value-impurityc %} {% if ffb.impurity == "C" %} selected {% endif %} {% endblock Value-impurityc %}>C</option>
                                        </select>
                                        
                                    </div>
                                </div>
                            </div>
                    </div>
                </div> 
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">ยกเลิก</button>
                    {% block modal-submit %}<button type="submit" onclick="showToast()" class="btn btn-success" ><i class="far fa-save"></i> บันทึก </button>{% endblock modal-submit %}
                </div>   
            </form>
        </div>
    </div>
</div>

ispproject/templates/palm/edit_rpo_po.html
<!-- Edit FFB  -->
{% extends "palm/add_rpo_po.html" %}
<!-- Edit Myapp  -->
{% block modal-id %} id="edit_ffb_Modal{{ffb.id}}" {% endblock modal-id %} data-backdrop

{% block modal-title %}<i calss="fas fa-plus"><i calss="fas fa-plus"></i>&nbsp;&nbsp; Edit  {% endblock modal-title %}
                
<!-- -- Form -- -->
{% block Action %} action="/edit_f/{{ffb.id}}" {% endblock Action %}

{% block Value-id %} {% endblock Value-id %}

{% block Value-poinvid %} Value= "{{ ffb.poinvid }}" {% endblock Value-poinvid %}
{% block Value-billid %} Value= "{{ ffb.billid }}" {% endblock Value-billid %}
{% block Value-vendorcardid %} Value= "{{ ffb.vendorcardid }}" {% endblock Value-vendorcardid %}
{% block Value-typecarid %} Value= "{{ ffb.typecarid }}" {% endblock Value-typecarid %}
{% block Value-goodib %} Value= "{{ ffb.goodib }}" {% endblock Value-goodib %}
{% block Value-goodob %} Value= "{{ ffb.goodob }}" {% endblock Value-goodob %}
{% block Value-goodnet %} Value= "{{ ffb.goodnet }}" {% endblock Value-goodnet %}
{% block Value-price1 %} Value= "{{ ffb.price1 }}" {% endblock Value-price1 %}
{% block Value-amnt1 %} Value= "{{ ffb.amnt1 }}" {% endblock Value-amnt1 %}
{% block Value-vendorcode %} Value= "{{ ffb.vendorcode }}" {% endblock Value-vendorcode %}
{% block Value-vendorname %} Value= "{{ ffb.vendorname }}" {% endblock Value-vendorname %}

{% block Value-gradea %} {% if ffb.grade == "A" %} selected {% endif %} {% endblock Value-gradea %}
{% block Value-gradeb %} {% if ffb.grade == "B" %} selected {% endif %} {% endblock Value-gradeb %}
{% block Value-gradec %} {% if ffb.grade == "C" %} selected {% endif %} {% endblock Value-gradec %}

{% block Value-impuritya %} {% if ffb.impurity == "A" %} selected {% endif %} {% endblock Value-impuritya %}
{% block Value-impurityb %} {% if ffb.impurity == "B" %} selected {% endif %} {% endblock Value-impurityb %}
{% block Value-impurityc %} {% if ffb.impurity == "C" %} selected {% endif %} {% endblock Value-impurityc %}

{% block modal-submit %}<button type="submit"  class="btn btn-warning"><i class="far fa-save"></i> อัพเดท </button>{% endblock modal-submit %}

ispproject/templates/palm/rpo_po.html
{% extends "layouts/base.html" %}
{% block name %}
<div class="sidebar-brand-text mx-3">ISANPALM</div>
{% endblock %}

{% block Dashboard %}
<li class="nav-item active">
    <a class="nav-link" href="rpo_po">
    <i class="fas fa-fw fa-tachometer-alt"></i>
    <span>ฝ่ายจัดซื้อปาล์ม</span></a>    
</li>
{% endblock Dashboard %}
                  

{% block content %}
    <div class="row">
        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100">
                <div class="card-body">
                    <div class="row no-gutters align-items-center py-0">
                        <div class="col">
                            <div class="text-xs font-weight-bold text-success text-uppercase">
                                <h3>เกษตรกร</h3></div>
                            <div class="h3 mb-0 font-weight-bold text-gray-800">
                                {{total_vendorcode_farmer_sum}} Kg.
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-0">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                                <h3>ลานเท</h3></div>
                            <div class="h3 mb-0 font-weight-bold text-gray-800">{{total_vendorcode_ramps_sum}} Kg.</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-0">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-1">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"><h3>ยอดรวมปริมาณผลปาล์ม</h3>
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h3 mb-0 mr-1 font-weight-bold text-gray-800">{{ total_sum_thousands}} Kg.</div>
                                </div>
                                <!-- <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-info" role="progressbar"
                                            style="width: 50%" aria-valuenow="{{ total_sum }}"
                                            aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div> -->
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pending Requests Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-0">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1"><h3>จำนวนรายการ</h3></div>
                            <div class="h3 mb-0 font-weight-bold text-gray-800 flex-end">{{total_count}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Begin Page Content -->
        <div class="col-lg-12">
            <!-- Page Heading -->
            <!-- <h1 class="h1 mb-4 text-gray-800 text-center">รายการซื้อผลปาล์ม </h1> -->
            <div class="col">
                <div class="row justify-content-end py">
                    <div class="col">
                        <!-- <button class="btn btn-outline-warning" data-toggle="modal" data-target="#SetVal_PO_Modal"><i class="fas fa-cogs"></i></button>
                        <button class="btn btn-outline-primary" data-toggle="modal" data-target="#VendorModal"><i class="fas fa-user-edit"></i></i></button> -->
                        
                    </div>
                </div>
            </div>
            <!-- DataTales Example -->
            <div class="card shadow">
                <div class="card-header py-3">
                    <div class="row d-flex">
                        <div class="col">
                            <h4 class="m-0 font-weight-bold text-center">ตารางแสดงรายการซื้อผลปาล์ม {% if x in all_empvendor %}{{x.VendorName}}{% endif%}</h4>
                            <button class="btn btn-outline-success" data-toggle="modal" data-target="#add_ffb_Modal" ><i class="fas fa-file-invoice"> บันทึกข้อมูล</i></button>
                        </div>
                        
                    </div>
                    {% if messages %}
                        {% for messages in messages %}  
                        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                            <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                              <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                            </symbol>
                            <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
                              <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
                            </symbol>
                            <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                              <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                            </symbol>
                          </svg>
                          
                          <div class="alert alert-success mt-2  d-flex align-items-center" role="alert">
                            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
                            <div>
                                <strong>{{messages}}</strong>
                            </div>
                          </div>
                          
                        {% endfor %}
                    {% endif %}
                    <div class="card-body py-2 ">
                        <div class="table-responsive">
                            <table class="table table-hover nowrap text-dark font-weight-bold" id="tb_PO" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th class="texe text-center">ลำดับ</th>
                                        <th class="texe text-center">วันที่</th>
                                        <th class="texe text-center">PO</th>
                                        <th class="texe text-center">รหัสบิล</th>
                                        <th class="texe text-center">ประเภทรถ</th>
                                        <th class="texe text-center">ทะเบียนรถ</th>
                                        <th class="texe text-center">รหัสลูกค้า</th>
                                        <th class="texe text-center">ชื่อลูกค้า</th>
                                        <th class="texe text-center">ขาเข้า</th>
                                        <th class="texe text-center">ขาออก</th>
                                        <th class="texe text-center">สุทธิ</th>
                                        <th class="texe text-center">ราคา</th>
                                        <th class="texe text-center">เกรด</th>
                                        <th class="texe text-center">เจือปน</th>
                                        <th colspan="2"class="texe text-center">เพิ่มเติม</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for ffb in all_ffb %} 
                                    <tr>
                                        <th scope="row" class="texe text-center align-middle">{{ forloop.counter }}</th>
                                        <td class="texe text-center align-middle">{{ ffb.docudate|date:"d/m/Y" }}</td>
                                        <td class="texe text-center align-middle">{{ffb.poinvid}}</td>
                                        <td class="texe text-center align-middle">{{ffb.billid}}</td>
                                        <td class="texe text-center align-middle">{{ffb.typecarid}}</td>
                                        <td class="texe text-center align-middle">{{ffb.vendorcardid}}</td>
                                        <td class="texe text-center align-middle">{{ffb.vendorcode}}</td>
                                        <td class="texe text-center align-middle">{{ffb.vendorname}}</td>
                                        <td class="texe text-center align-middle">{{ffb.goodib}}</td>
                                        <td class="texe text-center align-middle">{{ffb.goodob}}</td>
                                        <td class="texe text-center align-middle">{{ffb.goodnet}}</td>
                                        <td class="texe text-center align-middle">{{ffb.price1}}</td>
                                        <td class="texe text-center align-middle">{{ffb.grade}}</td>
                                        <td class="texe text-center align-middle">{{ffb.impurity}}</td>
                                        <td class="texe text-center align-middle"><button class="btn btn-warning" data-toggle="modal" data-target="#edit_ffb_Modal{{ffb.id}}"><i class="far fa-edit text"></i></button>
                                            <a class=" btn btn-danger far fa-trash-alt" href="delete_f/{{ffb.id}}" 
                                            onclick="return confirm('คุณต้องการลบข้อมูล {{ffb.id}} หรือไม่ ?')" 
                                            ></a>
                                        </td>
                                      </tr>
                                     {% include 'palm/edit_rpo_po.html' %}

                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                            <ul class="pagination">
                                {% if current_page.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{ current_page.previous_page_number }}">Previous</a></li>
                                {% else %}
                                <li class="page-item disabled"><span class="page-link">Previous</span></li>
                                {% endif %}
                        
                                {% for i in current_page.paginator.page_range %}
                                    {% if current_page.number == i %}
                                    <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                                    {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                
                                {% if current_page.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ current_page.next_page_number }}">Next</a></li>
                                {% else %}
                                <li class="page-item disabled"><span class="page-link">Next</span></li>
                                {% endif %}
                            </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<script>

    {% include 'palm/add_rpo_po.html' %}
    
    

{% endblock %}